### ISSUE TITLE
Desenvolvimento da tela de Dashboard do Produtor

### ISSUE THREAD

**Issue by marioguiW** [Grupo01-Biopark/Queijos-Finos-DEFINITIVO#15]
# Titulo
Desenvolvimento da tela de Dashboard do Produtor

## Descrição
Desenvolver uma tela que apresente os dados do produtor completos, com Nome, Endereço, Telefone, Telefone 2, CPF, CNPJ, Status, Certificações e Observações.

## Possíveis impedimentos
1. **Banco de dados inacabado:** A conclusão da tela pode ser afetada se o banco de dados não estiver totalmente configurado ou se os dados necessários não estiverem disponíveis.

## Passo a passo
1. **Criação da Branch para Desenvolvimento:** Criar uma nova branch com o título da issue que será desenvolvida.

2. **Criação da Tela de Dashboard:** Desenvolver a tela de acordo com o layout fornecido no Figma, garantindo que todos os dados do produtor sejam exibidos corretamente.

3. **Integração com o Back-end/Banco de Dados:** Conectar a tela ao back-end ou banco de dados para buscar e exibir os dados do produtor.

4. **Commit na Branch Criada:** Commitar todas as alterações na branch criada para que possam ser revisadas e integradas à branch principal posteriormente.

**Comment by carlosbarros007** [comment]
![Image](https://github.com/Grupo01-Biopark/Queijos-Finos-DEFINITIVO/assets/107757656/9a8a473e-5e73-4445-a708-50db18f9e127)

Tela em desenvolvimento
